Fix `install_cmd` command for cwltool
Following changes upstream in https://github.com/common-workflow-language/cwltool/commit/284a14587b1f648a19c9eb01fba73908c9c44ac0, mypy_primer is failing to execute the `install_cmd` command for cwltool:

```
subprocess.CalledProcessError: Command 'uv pip install --python /tmp/mypy_primer/projects/_cwltool_venv/bin/python $(grep -v mypy mypy-requirements.txt) -r requirements.txt' returned non-zero exit status 2.
```

The error being returned by uv is:

```
error: Failed to parse: `pydantic==2.12.0a1;`
  Caused by: Expected marker value, found end of dependency specification
pydantic==2.12.0a1;
                   ^
```

This is a quick fix that should get everything green again: just ignore all dependency lines in mypy-requirements.txt that contain semicolons